services:
  app_server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 9000:9000
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://lal:3%25b1aAeb@db:5432/link
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=link
      - POSTGRES_USER=lal
      - POSTGRES_PASSWORD=3%b1aAeb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
