FROM rust:1.74-alpine
WORKDIR /app
RUN apk add alpine-sdk openssl-dev tini
RUN RUSTFLAGS="-Ctarget-feature=-crt-static" cargo install sqlx-cli cargo-watch
CMD [ "ash", "-c", "cargo watch -c -w src -x run" ]